<?php
//Constantes Generales

//Header
define("CREAR_CURSO_HEADER",     	t("Crear curso"));


//Titulos del formulario de alta y edición de cursos
define("TITULO_FORMULARIO_CURSO",     		t("Creación/Edición de curso"));




//constantes para el menu principal de cuenta
define("INFORMACION_GENERAL",     	t("Información General"));
define("CONTACTO",                	t("Contacto"));
define("DIRECCIONES",             	t("Dirección(es)"));
define("PROFESIONAL_ACADEMICA",   	t("Profesional y Académica"));
define("INTERESES",  				t("Intereses"));
define("PRIVACIDAD",          		t("Configuración de Privacidad"));
define("FACTURACION",           	t("Datos de Facturación"));
define("PAGO",             			t("Datos de Pago"));
define("CUENTAS",               	t("Cuentas de Depósito"));
define("VERIFICACION_CUENTA",       t("Verificación de Cuenta"));
define("HISTORIAL_COMPRAS",         t("Historial de Compras"));
define("HISTORIAL_VENTAS",          t("Historial de Ventas"));
define("CAMBIO_PERFIL",             t("Cambia el tipo de perfil"));

define("AGRADECIMIENTO_PASO_FINAL_CURSOS", t("Configuración de cuenta concluida"));




//Titulos del formulario de configuración de cuenta
define("TITULO_FORMULARIO_CUENTA",     	t("Configuración de la Cuenta"));




//Constantes para el menú principal de configuración de cursos
define("DESCRIPCION_OBJETIVOS",         t("Descripción y Objetivos"));
define("DETALLES_CURSO",                t("Detalles del Curso"));
define("EVALUACION",                    t("Evaluación"));
define("IMAGEN_VIDEO",                  t("Imágen y Video"));
define("BIBLIOGRAFIA_RECOMENDACIONES",  t("Bibliografías y Recomendaciones"));
define("PREGUNTAS_FRECUENTES",          t("Preguntas Frecuentes"));
define("CONFIGURACION_PAGOS",           t("Configuración de Pagos"));
define("DATOS_ESPECIFICOS",             t("Datos Específicos"));
define("SELECCION_CANAL",               t("Selección de Canal"));
define("CONFIGURACION_LMS",             t("Configuración de LMS"));

define("AGRADECIMIENTO_PASO_FINAL_CUENTA", t("Configuración de cuenta concluida"));





//BOTONES DE NAVEGACIÓN PARA LOS FORMULARIOS

define("BOTON_ANTERIOR", t("Atrás"));
define("BOTON_GUARDAR", t("Guardar"));
define("BOTON_SIGUIENTE", t("Siguiente"));
define("BOTON_VISTA_PREVIA", t("Siguiente"));
define("FILTRO_INTERVALO", t("Ordenes en"));
define("FILTRO_ENTREGA", t(""));
define("FILTRO_ESTATUS", t(""));
define("FILTRO_VENTAS", t(""));
define("ORDENAMIENTO_VENTAS", t(""));
define("ORDEN_HISTORIAL", t(""));

define("HISTORIAL_VENTA_NUM_RASTREO", t("Subir No. de Rastreo"));
define("HISTORIAL_VENTA_VALORACION", t("Pedir Valoración"));

//Textos genéricos
define("TITULO_FORMULARIO_COMPLETO",		t("Terminado"));


define('ACADEMIA',         t('Academia'));
define('AGREGAR_CUENTA',         t('Agregar Cuenta'));
define('AGREGAR_DIRECCION',         t('Agregar Dirección'));
define('AGREGAR_ESTUDIO',         t('Agregar Estudio'));
define('AGREGAR_INTERES',         t('Agregar'));
define('AGREGAR_PAYPAL',         t('Agregar cuenta de PayPal'));
define('AGREGAR_PUESTO',         t('Agregar Puesto'));
define('ALIAS_CUENTA',         t('Alias de cuenta'));
define('ALIAS_TARJETA',         t('Alias de la tarjeta'));
define('ANIO_FIN',         t('Año de Fin'));
define('ANIO_INICIO',         t('Año de Inicio'));
define('ANIO_VENCIMIENTO_TARJETA',         t('Año de Vencimiento'));
define('CALLE',         t('Calle'));
define('CAMBIO_PERFIL_EMPRESA',         t('Cambiar de perfil a Empresa'));
define('CIUDAD',         t('Ciudad'));
define('CLABE',         t('CLABE Intervancaria'));
define('COLONIA',         t('Colonia'));
define('COMPANIA',         t('Compañía'));
define('CONTACTO_NOMBRE',         t('Contacto'));
define('CONTRASENIA',         t('Contraseña'));
define('CORREO_PAYPAL',         t('Correo de PayPal'));
define('CP',         t('Código Postal'));
define('CURSOS',         t('Cursos'));
define('DEL_MUNIC',         t('Delegación o municipio'));
define('DELEG',         t('Delegación o Municipio'));
define('DIR_EXISTENTE',         t('Dirección existente'));
define('DOC_DOMICILIO',         t('Documento de Domicilio'));
define('DOC_IDENTIFICACION',         t('Documento de Identificación'));
define('ELIMINAR_CUENTA',         t('Eliminar Cuenta'));
define('ELIMINAR_DIRECCION',         t('Eliminar Dirección'));
define('EMAIL',         t('Correo Electrónico'));
define('EMAIL_2',         t('Correo Electrónico Alternativo'));
define('EMP_ACTUAL',         t('¿Es su empleo actual?'));
define('ESCUELA',         t('Escuela'));
define('ESTADO',         t('Estado'));
define('ESTUDIO_CURSNDO',         t('¿Actualmente cursando?'));
define('FACEBOOK',         t('Cuenta de Facebook'));
define('FECHA_INGRESO',         t('Fecha de Ingreso'));
define('GRUPOS',         t('Grupos'));
define('INTERES',         t('Selecciona Interes'));
define('MENSAJES',         t('Mensajes'));
define('MES_FIN',         t('Mes de fin'));
define('MES_INICIO',         t('Mes de Inicio'));
define('MES_VENCIMIENTO_TARJETA',         t('Fecha de vencimiento'));
define('NO_EXTERIOR',         t('Número Exterior'));
define('NO_INTERIOR',         t('Número Interior'));
define('NOMBRE_BANCO',         t('Nombre del banco'));
define('NOMBRE_TARJETA',         t('Nombre de tarjeta'));
define('NOMBRE_TITULAR',         t('Nombre del Titular'));
define('NUMERO_CUENTA',         t('Número de Cuenta'));
define('NUMERO_TARJETA',         t('Número de Tarjeta'));
define('OTRO_INTERES',         t('Otro interes '));
define('PAIS',         t('País'));
define('PERFIL',         t('Perfil'));
define('TIPO_PERSONA',         t('Persona'));
define('PERSONAL',         t('Personal'));
define('PORTAFOLIO',         t('Portafolio'));
define('PRODUCTOS',         t('Productos'));
define('PROFESIONAL',         t('Profesional'));
define('RAZON_SOCIAL',         t('Razon Social'));
define('REDES',         t('Redes'));
define('RFC',         t('RFC'));
define('SEXO',         t('Género'));
define('SITIO_WEB',         t('Sitio web'));
define('SKYPE',         t('Cuenta de Skype'));
define('TEL_CASA',         t('Telefono de Casa'));
define('TEL_MOVIL',         t('Telefono móvil'));
define('TEL_OFICINA',         t('Telefono de Oficina'));
define('TEL_OTRO',         t('Telefono adicional'));
define('TELEFONO',         t('Telefono'));
define('TIPO_CUENTA',         t('Tipo de Cuenta'));
define('TIPO_ESTUDIO',         t('Tipo de Estudio'));
define('TIPO_TARJETA',         t('Tipo de Tarjeta'));
define('TIT_ESTUDIOS',         t('Título obtenido'));
define('TIT_PUESTO',         t('Título o puesto'));
define('TWITTER',         t('Cuenta de Twitter'));
define('FECHA_NACIMIENTO',         t('Fecha de Nacimiento'));





//Radios de creación de curso, paso "detalles del curso"
define('HORAS_TRABAJO',         t('Horas de Trabajo'));
define('SEMANAS_TOTALES',         t('Semanas Totales'));
define('ABIERTO',         t('Abierto'));
define('CERRADO',         t('Cerrado'));
define('SI',         t('Si'));
define('NO',         t('No'));
define('TUTOREO_PERSONALIZADO',         t('Personalizado'));
define('TUTOREO_AUTOESTUDIO',         t('Autoestudio/Autodirigido'));




//Variables para los cursos 
define('',         t('Datos específicos'));
define('ACREDITACION',         t('Acreditación'));
define('AGREGAR_PREGUNTA_FRECUENTE',         t('Agregar Otra Pregunta'));
define('AGREGAR_PRODUCTO_BOTON',         t('Agregar'));
define('AGREGAR_PRODUCTO_TEXTO',         t('Agrega la liga de los productos que recomiendas para tu curso'));
define('AGREGAR_PROFESOR',         t('Agregar Profesor'));
define('BIBLIOGRAFIA_OFICIAL',         t('Bibliografía oficial'));
define('BIBLIOGRAFIA_RECOMENDADA',         t('Bibliografía recomendada'));
define('CADUCIDAD',         t('Caducidad'));
define('CERTIFICADO_CSD',         t('Sube tu Certificado de Sello Digital CSD:'));
define('COLABORACION',         t('Colaboración'));
define('COMPROBANTE_FISCAL',         t('¿Cuentas con comprobante fiscal?'));
define('CORREO_RESPONSABLE_TECNICO',         t('Correo electrónico del responsible técnico'));
define('COSTO_CURSO',         t('Costo del curso'));
define('CUENTA_DEPOSITO',         t('Selecciona tu cuenta de depósito'));
define('CURSO_GRATUITO',         t('Curso gratuito'));
define('DESCUENTO_CURSO',         t('Descuento'));

define('DONAR_CURSO',         t('¿Quieres donar?'));
define('DURACION_CURSO',         t('Duración del curso'));
define('ELIMINAR_PREGUNTA_FRECUENTE',         t('Eliminar'));

define('FECHA_IMPARTICION',         t('Fechas de impartición'));
define('FIN',         t('Fecha de fin'));
define('GENERAR_CONT',         t('¿VAS A GENERAR EL CONTENIDO DE TU CURSO EN LA PLATAFORMA FUTUREED?'));
define('ID_CURSO',         t('ID del curso'));
define('INICIO',         t('Fecha de inicio'));
define('LIMITE_ALUMNOS',         t('Límite de alumnos'));
define('METODOLOGIA',         t('Metodología'));
define('MODALIDAD',         t('Modalidad'));
define('MODULO_CERTIFICADO',         t('Módulo o certificado'));
define('MONTO_DONAR',         t('¿Cuánto?'));
define('NUMERO_ALUMNOS',         t('Número de alumnos'));
define('POR_SEMANA',         t('Por semana'));
define('PREGUNTA_FRECUENTE',         t('Pregunta'));
define('REQUERIMIENTOS',         t('Requerimientos previos del curso'));
define('RESPUESTA_PREG_FRECUENTE',         t('Respuesta'));
define('SELECT_PROFESOR',         t('Profesor(es)'));
define('SOPORTE_TECNICO',         t('¿CUENTAS CON SOPORTE TÉCNICO PARA HACER LA CONEXIÓN AUTOMÁTICA DE TU CURSO?'));
define('SUBIR_IMAGEN',         t('Sube una Imagen'));
define('SUBIR_VIDEO',         t('Pon la liga de tu video en el campo'));
define('TEMARIO',         t('Temario'));
define('TOTALES',         t('Totales'));
define('TUTOREO',         t('Tutoreo'));
define('URL_CALLBACK',         t('URL de callback'));
define('URL_LMS',         t('URL específico de LMS'));
define('URL_PORTAL',         t('URL de portal'));

define('SEMANA',         t('semana'));
define('SEMANAS',         t('semanas'));

define('DATOS_ALUMNO_PERSONALES',         t('Datos Personales'));
define('DATOS_ALUMNO_ESCUELA',         t('Datos de Escuela Donde Labora'));
define('DATOS_ALUMNO_BECA',         t('Datos de Beca'));



define ('TITULO_TELEFONOS', t('TELÉFONO(S)'));
define ('TITULO_EMAIL', t('CORREO ELECTRÓNICO'));
define ('TITULO_OTROS_CONTACTO', t('OTROS'));
define ('CAMPOS_OBLIGATORIOS', t('Campos Obligatorios'));
define ('DIRECCION_POSTAL', t('DIRECCIÓN POSTAL'));
define ('DIRECCION_ENVIO', t('DIRECCIÓN DE ENVÍO'));
define ('INFORMACION_PROFESIONAL', t('INFORMACIÓN PROFESIONAL'));
define ('INFORMACION_ACADEMICA', t('INFORMACIÓN ACADÉMICA'));
define ('AREAS_INTERES', t('SELECCIONA LAS ÁREAS QUE TE INTERESAN *Es obligatorio que selecciones por lo menos uno*'));
define ('PRIVACIDAD_PERFIL', t('PERFIL'));
define ('PRIVACIDAD_INFORMACION', t('INFORMACIÓN'));
define ('PRIVACIDAD_SECCIONES', t('SECCIONES'));
define ('PRIVACIDAD_MENSAJERIA', t('MENSAJERÍA'));
define ('TIPO_PERSONA_TITULO', t('TIPO DE PERSONA'));
define ('DOMICILIO_FISCAL', t('DOMICILIO FISCAL'));
define ('TARJETAS_CREDITO', t('TARJETAS DE CRÉDITO'));
define ('CUENTAS_DEPOSITO', t('CUENTAS DE DEPÓSITO'));
define ('CUENTA_PAYPAL', t('CUENTAS DE PAYPAL'));
define ('VERIFICACION_USUARIO', t('VERIFICACIÓN DE USUARIO'));

define ('PRIVADO', t('Público'));
define ('PUBLICO', t('Privado'));
define ('MORAL', t('Moral'));
define ('FISICA', t('Fisica'));

define ('MASTERCARD', t('Mastercard'));
define ('VISA', t('Visa'));

define ('CODIGO_SEGURIDAD_TARJETA', t('Código de Seguridad.'));

define ('AGREGAR_TARJETA', t('Agregar Tarjeta'));
define ('ELIMINAR_TARJETA', t('Eliminar Tarjeta'));


/*------------------------------- AGREGADOS POR DAVE 28/11/2014 FILTROS LISTADO CURSOS-----------------------------*/
define ('ORDENAR_POR', t('Ordenar por'));
define ('FILTROS_AVANZADOS', t('Filtros avanzados'));
define ('PRESENCIAL', t('Presencial'));
define ('ONLINE', t('Online'));
define ('SEMIPRESENCIAL', t('Semipresencial'));
define ('LICENCIATURA', t('Licenciatura'));
define ('MAESTRIA', t('Maestría'));
define ('TALLER', t('Taller'));
define ('DIPLOMADO', t('Diplomado'));
define ('DOCTORADO', t('Doctorado'));
define ('CERTIFICACIÓN', t('Certificación'));
define ('PRECIO', t('Precio'));
define ('O_MAS', t('O más'));
define ('POR_PRECIO_ASCENDENTE', t('Por precio ascendente'));
define ('POR_PRECIO_DESCENDENTE', t('Por precio descendente'));
define ('POR_VALORACION_ASCENDENTE', t('Por valoración ascendente'));
define ('POR_VALORACION_DESCENDENTE', t('Por valoración descendente'));
define ('POR_FECHA_INICIO_ASCENDENTE', t('Por fecha de inicio ascendente'));
define ('POR_FECHA_INICIO_DESCENDENTE', t('Por fecha de inicio descendente'));
define ('POR_DURACION_ASCENDENTE', t('Por duración ascendente'));
define ('POR_DURACION_DESCENDENTE', t('Por duración descendente'));
define ('TODOS', t('Todos'));

/*----------------------------FIN AGREGADOS POR DAVE 28/11/2014 FILTROS LISTADO CURSOS-----------------------------*/

/*------------------------------- AGREGADOS POR DAVE CARRUSELES PERFIL -----------------------------*/
define ('SUGERIR_CURSO', t('Sugerir curso'));
define ('SUGERIR_GRUPO', t('Sugerir grupo'));
define ('SUGERIR_CANAL', t('Sugerir canal'));
define ('NO_TIENE_CURSOS_ACTIVOS', t('no tiene cursos activos.'));
define ('NO_TIENE_GRUPOS_ACTIVOS', t('no tiene grupos activos.'));
define ('NO_TIENE_CANALES_ACTIVOS', t('no tiene canales activos.'));
define ('PUEDES_SUGERIRLE_UN_CURSO', t('Puedes sugerirle un curso.'));
define ('PUEDES_SUGERIRLE_UN_GRUPO', t('Puedes sugerirle un grupo.'));
define ('PUEDES_SUGERIRLE_UN_CANAL', t('Puedes sugerirle un canal.'));
/*----------------------------FIN AGREGADOS POR DAVE CARRUSELES PERFIL ------------------------------*/

/*------------------------------- AGREGADOS POR DAVE LISTADOS CURSOS -----------------------------*/
define('USUARIOS_POPULARES', t('Usuarios populares'));
define('CALIFICAR', t('Calificar'));

/*--------------------------- FIN AGREGADOS POR DAVE LISTADOS CURSOS -----------------------------*/

define ('TITULO_PRIVACIDAD_PERFIL', t('PERFIL'));
define ('TEXTO_PRIVACIDAD_PERFIL', t('Privado: asdfsadfsdafsadf asdsfdsafdasdf'));
define ('TITULO_PRIVACIDAD_INFO', t('INFORMACIÓN'));
define ('TEXTO_PRIVACIDAD_INFO', t('Privado: asdfsadfsdafsadf asdsfdsafdasdf'));
define ('TITULO_PRIVACIDAD_SECCIONES', t('SECCIONES'));
define ('TEXTO_PRIVACIDAD_SECCIONES', t('Privado:asdfsadfsdafsadf asdsfdsafdasdf'));
define ('TITULO_PRIVACIDAD_MENSAJERIA', t('MENSAJERÍA'));
define ('TEXTO_PRIVACIDAD_MENSAJERIA', t('Privado: asdfsadfsdafsadf asdsfdsafdasdf'));

define ('DIRECCION_EXISTENTE', t('La dirección de envío es la misma que una de las dadas de alta anteriormente'));
define ('SEL_DIRECCION_EXISTENTE', t('Selecciona una.'));



define('NOMBRE_CURSO',         t('Nombre del curso'));
define('DESCRIPCION_CURSO',         t('Descripción'));
define('OBJETIVO_CURSO',         t('Objetivo'));
define('AUDIENCIA_CURSO',         t('Audiencia a la que el curso está dirigida'));
define('CATEGORIA_CURSO',         t('Categoría'));
define('SUBCATEGORIA_CURSO',         t('Subcategoría'));
define('BOTON_SUBCATEGORIA',         t('AGREGAR SUBCATEGORIA'));
define('IDIOMA',         t('Idioma'));

define ('TITULO_PREG_FRECUENTE', t('INTRODUCE LAS PREGUNTAS CON SU RESPUESTA'));
define ('TIP_CUENTA_DEPOSITO', t('Tip: Recuerda que tienes que ligar tu curso a una cuenta para que puedas recibir tus ingresos.'));
define ('TIP_COMPROBANTE_FISCAL', t('Tip: Texto explicativo del comprobante fiscal.'));
define ('TIP_CONTENIDO_FUTUREED', t('Tip: Texto explicativo del contenido de future ed.'));
define ('TIP_CONTENIDO_CANAL', t('Texto explicativo con sugerencias de por qué es bueno organizar los cursos en canales.'));




//Formulario de Login
define ('TITULO_LOGIN', t('Iniciar Sesión'));
define ('LOGIN_NOMBRE', t('Nombre de Usuario o correo electrónico'));
define ('LOGIN_CONTRASENA', t('Contraseña'));







//Modulo Perfil
/*Canales*/
//Formulario de Crear Canal
define('NOMBRE', t('Nombre'));
define('TIPS_NOMBRE', t('Tip: Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto.'));
define('PLACEHOLDER_NOMBRE', t('Ingresa tu nombre ... '));

define('DESCRIPCION', t('Descripcion del Canal'));
define('TIPS_DESCRIPCION', t('Tip: Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto.'));
define('PLACEHOLDER_DESCRIPCION', t('Ingresa la descripcion ... '));

define('CREADOR', t('Creador'));
define('PROPIETARIO', t('Propietario'));


define ('LOGIN_BOTON', t('ENTRAR'));
define ('LOGIN_RECORDARME', t('Recordar mis datos'));
define ('CONTRASENA_OLVIDADA', t('Olvidé mi contraseña'));
define ('INICIAR_SESION_REDES_SOCIALES', t('Iniciar sesión con'));
define ('REGISTRAR_USUARIO', t('¿No estás registrado aún?'));
define ('REGISTRAR_USUARIO_BOTON', t('REGÍSTRATE AQUÍ'));

/*Usuarios Sugeridos*/
define('USUARIOS_SUGERIDOS', t('USUARIOS SUGERIDOS'));
define('VER_MAS', t('Ver Mas'));
define('SIGUIENDO', t('Siguiendo'));


//Showcases
define('SHOWCASE_ARCHIVO',         t('Archivo'));
define('SHOWCASE_NOMBRE_PROYECTO',         t('Nombre del Proyecto'));
define('SHOWCASE_INFO_PROYECTO',         t('Infromación del Proyecto'));
define('SHOWCASE_CURSO',         t('Curso:'));
define('SHOWCASE_CATEGORIA',         t('Categoría:'));
define('SHOWCASE_FECHA',         t('Fecha:'));
define('SHOWCASE_FOTOGRAFIA',         t('Fotografía del proyecto'));

define('CATEGORIA', t('Categoria'));
define('TIPS_CATEGORIA', t('Tip: Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto.'));

define('SUBCATEGORIA', t('Subcategoria'));
define('TIPS_SUBCATEGORIA', t('Tip: Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto.'));

define('IMAGEN', t('Imagen'));
define('TIPS_IMAGEN', t('Tip: Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto.'));




//Grupos
define('GRUPO_NOMBRE',         t('Nombre del Grupo:'));
define('GRUPO_DESCRIPCION',         t('Descripción:'));
define('GRUPO_IMAGEN',         t('Imagen del Grupo:'));
define('GRUPO_CATEGORIA',         t('Categoría:'));
define('GRUPO_SUBCATEGORIA',         t('Subcategoría:'));
define('GRUPO_CURSO',         t('Curso:'));
define('GRUPO_MIEMBROS',         t('Miembros:'));
define('GRUPO_PRIVACIDAD',         t('Privacidad:'));
define('GRUPO_ETIQUETAS',         t('Etiquetas:'));
define('BOTON_CREAR_GRUPO',         t('Crear Grupo'));

define('TUTORES', t('Tutores'));
define('TIPS_TUTORES', t('¿Para que?: Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto.'));
define('PLACEHOLDER_TUTORES', t('Agrega Tutores ... '));
define('AGREGAR_TUTORES', t('Agregar'));

define('AGREGAR_CURSOS', t('Agregar Cursos'));
define('TIPS_AGREGAR_CURSOS', t('Tip: Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto.'));
define('PLACEHOLDER_AGREGAR_CURSOS', t('Agrega Cursos ... '));
define('BOTON_AGREGAR_CURSOS', t('Agregar'));

define('ADMINISTRADORES', t('Administradores'));
define('TIPS_ADMINISTRADORES', t('¿Para que?: Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto.'));
define('PLACEHOLDER_ADMINISTRADORES', t('Ingresa Administradores ... '));
define('AGREGAR_ADMINISTRADORES', t('Agregar'));

define('CANCELAR', t('Cancelar'));

define('CAMBIOS', t('Salvar Cambios'));




//Cursos
define ("CURSOS_ACTUALES", "Cursos Actuales");
define ("CURSOS_PASADOS", "Cursos Pasados");
define ("CURSOS_TOMAR", "Cursos por tomar");
define ("TODOS_CURSOS", "Todos los cursos");

define ("FECHA_DE_INICIO", "Fecha de inicio");
define ("TIPO_DE_CURSO", "Tipo de curso");
define ("ORDEN_ALFABETICO", "Orden alfabético");

//Cursos Comprados
define ("INICIA", "Inicia");
define ("TERMINA", "Termina");
define ("APOYO_FUNDACION", "Se está apoyando a la fundacion:");
define ("IR_CLASE", "Ir a clase");
//define ("CALIFICAR", "Calificar");
//Modales - Calificar
//define("", "");

//Cursos Creados
//define("", "");





//Modulo Curso
/*Ver Curso*/
define('PRECIO_FED', t('Precio FutureED'));
define('ANIADE_CARRITO',t('A&Ntilde;ADIR AL CARRITO'));
define('AGREGAR_CURSOS_TOMAR', t('AGREGAR A CURSOS POR TOMAR'));
define('SOBRE_TUTOR', t('SOBRE EL TUTOR'));
define('USUARIOS_GUSTADO_CURSO', t('Usuarios que les ha gustado el curso'));
define('OBJETIVOS_PRINCIPALES', t('OBJETIVOS PRINCIPALES'));
define('FECHAS_INICIAR_CURSO', t('PR&Oacute;XIMAS FECHAS PARA INICIAR EL CURSO'));
define('INFORMACION_CURSO', t('Informaci&oacute;n'));
define('PROYECTOS', t('Proyectos'));
define('CURSOS_POPULARES', t('Cursos populares'));
define('CURSO', t('Curso'));
define('TE_RESULTADO_UTIL_COMENTARIO' ,t('¿Te ha resultado útil este comentario?'));
define('VISTA_RAPIDA', t('VISTA R&Aacute;PIDA'));
define('OPCIONES_UTILES,ALUMNOS', t('Opiniones más útiles de alumnos que han tomado el curso'));
define('REQUISITOS_PREVIOS', t('REQUISITOS PREVIOS'));
define('CARGANDO', t('Cargando...'));
define('SE_APOYO_FUNDACION', t('Se apoyo a la fundacion'));

define('CURSOS_COMPRADOS', t('Cursos Comprados'));
define('CURSOS_CREADOS', t('Cursos Creados'));
define('TIPO_CURSO', t('Tipo Curso'));

define('INICIO_CURSO',t('Inicio de curso'));
define('FIN_CURSO', t('Fin de curso'));
define('TUTOR',t('Tutor'));
define('FECHA_INICIO', t('Fecha Inicio'));
define('ESTATUS', t('Estatus'));

/*Cursos Sugeridos*/
define('CURSOS_SUGERIDOS', t('CURSOS SUGERIDOS'));

//Modulo Canales - Ver Canal
//Formularios de Ver Canal
define('BUSQUEDA', t('BUSCAR'));
define('CANAL', t('Canal'));
define('PLACEHOLDER_BUSQUEDA', t('Buscar dentro del canal ... '));





//Modulo Red Social - Compartir
//Formularios de Modal - Iniciar Sesion
define('PLACEHOLDER_INICIAR_SESION_USUARIO', t('Usuario o Correo electronico'));
define('PLACEHOLDER_INICIAR_SESION_CONTRASENA', t('Contraseña'));
define('INICIAR_SESION_RECORDAR', t('Recordar mis datos'));
define('INICIAR_SESION_CONTRASEÑA', t('Olvide mi contraseña'));
define('INICIAR_SESION_BOTON1', t('Entrar'));
define('INICIAR_SESION_TXT', t('Aún no tienes cuenta'));
define('INICIAR_SESION_BOTON2', t('Registrate Aquí'));
//Formularios de Modal - Compartir FED
define('COMPARTIR_FED_TEXT', t('Compartir:'));
define('MENSAJE_TITULO',t('Mensaje:'));
define('PLACEHOLDER_MENSAJE', t('Escribe tu mensaje ...'));
define('COMPARTIR_FED_BOTON', t('Compartir'));
/*Opciones*/
define('BUSQUEDA_TEXT1', t('Buscar Usuario(s):'));
define('BUSQUEDA_TEXT2', t('Agrega varios usuarios separandolos con comas.'));
define('SELECT_TITULO', t('Seleccionar grupo:'));
//Formularios de Modal - Compartir Correo
define('COMPARTIR_CORREO_TEXT1', t('Enviar a:'));
define('PLACEHOLDER_COMPARTIR_CORREO_CAMPO', t('Escribe aqui el correo electronico'));
define('COMPARTIR_CORREO_TEXT2', t('Mensaje:'));
define('COMPARTIR_CORREO_BOTON', t('Compartir'));






//Grupos
define('TITULO_MIS_GRUPOS', t('Mis Grupos'));
define('TITULO_GRUPOS_ADMINISTRADOS', t('Grupos Administrados'));
define('TITULO_CREAR_GRUPO', t('+ Crear Grupo'));





//Modulo Fedcorefront - Home
//Formulario - Busqueda Principal
define('PLACEHOLDER_BUSQUEDA_PRINCIPAL', t('Hoy quisiera aprender sobre ...'));

//Home - Busqueda Principal
define('BUSQUEDA_BIENVENIDA1', t('¡El futuro lo creamos hoy!'));
define('BUSQUEDA_BIENVENIDA2', t('Aprende algo nuevo'));
define('BUSQUEDA_TEXTO1', t('¿Cómo funciona FutureED? Conócenos.'));

//Home - Fundaciones
define('FUNDACIONES_BIENVENIDA1', t('Por cada curso que compres una ayudas a una fundación. ¡Tú eliges cúal!'));
define('FUNDACIONES_LINK1', t('Conoce las fundaciones'));
define('FUNDACIONES_LINK2', t('Registra tu fundación'));

//Home - Cursos
define('CURSOS_TEXTO1', t('Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto.'));
define('CURSOS_TEXTO2', t('Lorem Ipsum es simplemente el texto de relleno de las imprentas.'));
define('CURSOS_LINK1', t('Busca más cursos'));
define('CURSOS_LINK2', t('Crea tu Curso'));
define('CURSOS_INVITACION', t('¿Te interesa dar a conocer tus cursos?'));
define('CURSOS_BOTON1', t('Crear Cursos'));
define('VER_CURSO', t('Ver Curso'));

//Home - Empresas
define('EMPRESAS', t('Empresas'));
define('EMPRESAS_TEXTO1', t('Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto.'));
define('EMPRESAS_TEXTO2', t('Lorem Ipsum es simplemente el texto de relleno de las imprentas.'));
define('EMPRESAS_LINK1', t('Busca otras empresas'));
define('EMPRESAS_LINK2', t('Registrate como empresa'));
define('EMPRESAS_INVITACION', t('¿Te interesa registrar tu empresa?'));
define('EMPRESAS_BOTON1', t('Crear Cuenta'));
define('VER_EMPRESA', t('Ver Empresa'));
define('SEGUIDORES', t('Seguidores'));
define('CANALES', t('Canales'));

//Home - Comunidad
define('COMUNIDAD', t('Comunidad'));
define('COMUNIDAD_BIENVENIDA1', t('¡Más de 10 millones de estudiantes y maestros de todo el mundo!'));
define('COMUNIDAD_TEXTO1', t('Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto.'));
define('COMUNIDAD_TEXTO2', t('Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto.'));
define('COMUNIDAD_LINK1', t('Conoce más acerca de la comunidad'));
define('COMUNIDAD_LINK2', t('Únete a nuestra comunidad'));
define('COMUNIDAD_INVITACION',  t('¡Forma parte de la comunidad FED!'));
define('COMUNIDAD_BOTON1', t('Registrarme'));
define('PRODUCTOS_INVITACION', t('¿Te interesa vender tus productos?'));
define('PRODUCTOS_BOTON1', t('Vender Productos'));

//Home - Facilidad de Pagos
define('FACILIDAD_PAGO', t('Facilidades de Pago'));
define('FACILIDAD_PAGO_TEXTO1', t('Realiza tus compras de manera sencilla, rápida y segura. Contamos con distintas formas de pago para tu comodidad.'));
define('FACILIDAD_PAGO_LINK1', t('Conoce más acerca de la comunidad'));
define('FACILIDAD_PAGO_LINK2', t('Únete a la comunidad'));
define('FACILIDAD_PAGO1', t('Deposito o transferencia con cualquier banco'));
define('FACILIDAD_PAGO2', t('Con tarjeta de crédito'));
define('FACILIDAD_PAGO3', t('Por medio de PayPal'));
define('FACILIDAD_PAGO4', t('En tu tienda OXXO más cercana'));



	define ("MIEMBROS", t("Miembros"));
	define ("ULTIMA_ACTIVIDAD", t("Última Actividad"));
	define ("TIPO_GRUPO", t("Este Grupo Es"));
	define ("INICIO_2", t("Inicia"));
	define ("TERMINO", t("Termina"));

	define("SIN_SUBCATEGORIA",t("Sin Subcategoría"));
	define("FORMATO_FECHA",t("dd/mm/yyyy"));

	define("MIS_CANALES",t("Mis canales"));
	define("CANALES_QUE_ADMINISTRO",t("Canales que Administro"));
//Modulo Busquedas
//Opciones
define("BUSQUEDA_TODOS", t("Todos"));
define("BUSQUEDA_CURSOS", t("Cursos"));
define("BUSQUEDA_EMPRESAS", t("Empresas"));
define("BUSQUEDA_USUARIOS", t("Usuarios"));
define("BUSQUEDA_CANALES", t("Canales"));
define("BUSQUEDA_GRUPOS", t("Grupos"));
//Contador
define("BUSQUEDA_CONTADOR_TXT1", t("Todos"));
define("BUSQUEDA_CONTADOR_TXT2", t("Resultados de"));

//Items - Cursos
//define("", "");

//Items - Empresas
//define("", "");

//Items - Usuarios
//define("", "");

//Items - Canales
//define("", "");

//Items - Grupos
//define("", "");

//Filtros - Empresas
define("UBICACION", "Ubicacion");
define("TIPO", "Tipo");

define("PLACEHOLDER_CONTRA_CAMBIAR", t("inserta la nueva contraseña de tu cuenta"));
define("MASCULINO", "Masculino");
define("FEMENINO", "Femenino");


define("LINKEDIN", "Linkedin");
define("FACEBOOK_CHAT", "Facebook chat");
define("HANGOUTS", "Hangouts");
define("GOOGLE_PLUS", "Google plus");


define("CONTACTO_MENSAJERIA", t("Mensajería Instantánea"));
define("CONTACTO_WEB", t("Sitio web"));
define("CONTACTO_REDES", t("Redes Sociales"));


define("TITULO_REGISTRO", t("¡Bienvenido a FutureEd!"));
define("SUBTITULO_REGISTRO", t("Registrar una cuenta nueva"));
