<?php    
    function obtener_notificaciones($uid)
    {
        $arrResultados = array();
    
        array_push($arrResultados,
                array(
                  'cantidad_notificaciones' => 2,
                  'cantidad_carrito' => 3,
                  'cantidad_wishlist' => 1
                  )
              );    
        return $arrResultados;      

    }
        
    ?>
    
    
    
    

 
     

    

