<?php

/*----------------------- Carrusel - Comunidad -----------------------*/
function consultar_carrusel_comunidad($uid){
  $arrResultados = array();

  array_push($arrResultados,
    array(
      'field_usuario_imagen' => 'http://placehold.it/50x50',
      'field_usuario_nombre' => 'Usuario1',
      'field_usuario_certificado' => 1,
    ),
    array(
      'field_usuario_imagen' => 'http://placehold.it/50x50',
      'field_usuario_nombre' => 'Usuario2',
      'field_usuario_certificado' => 1,
    ),
    array(
      'field_usuario_imagen' => 'http://placehold.it/50x50',
      'field_usuario_nombre' => 'Usuario3',
      'field_usuario_certificado' => 1,
    ),
    array(
      'field_usuario_imagen' => 'http://placehold.it/50x50',
      'field_usuario_nombre' => 'Usuario4',
      'field_usuario_certificado' => 1,
    ),
    array(
      'field_usuario_imagen' => 'http://placehold.it/50x50',
      'field_usuario_nombre' => 'Usuario5',
      'field_usuario_certificado' => 1,
    ),
    array(
      'field_usuario_imagen' => 'http://placehold.it/50x50',
      'field_usuario_nombre' => 'Usuario6',
      'field_usuario_certificado' => 1,
    ),
    array(
      'field_usuario_imagen' => 'http://placehold.it/50x50',
      'field_usuario_nombre' => 'Usuario7',
      'field_usuario_certificado' => 1,
    ),
    array(
      'field_usuario_imagen' => 'http://placehold.it/50x50',
      'field_usuario_nombre' => 'Usuario8',
      'field_usuario_certificado' => 1,
    ),
    array(
      'field_usuario_imagen' => 'http://placehold.it/50x50',
      'field_usuario_nombre' => 'Usuario9',
      'field_usuario_certificado' => 0,
    ),
    array(
      'field_usuario_imagen' => 'http://placehold.it/50x50',
      'field_usuario_nombre' => 'Usuario10',
      'field_usuario_certificado' => 0,
    ),
    array(
      'field_usuario_imagen' => 'http://placehold.it/50x50',
      'field_usuario_nombre' => 'Usuario11',
      'field_usuario_certificado' => 0,
    ),
    array(
      'field_usuario_imagen' => 'http://placehold.it/50x50',
      'field_usuario_nombre' => 'Usuario12',
      'field_usuario_certificado' => 0,
    ),
    array(
      'field_usuario_imagen' => 'http://placehold.it/50x50',
      'field_usuario_nombre' => 'Usuario13',
      'field_usuario_certificado' => 0,
    ),
    array(
      'field_usuario_imagen' => 'http://placehold.it/50x50',
      'field_usuario_nombre' => 'Usuario14',
      'field_usuario_certificado' => 0,
    ),
    array(
      'field_usuario_imagen' => 'http://placehold.it/50x50',
      'field_usuario_nombre' => 'Usuario15',
      'field_usuario_certificado' => 0,
    )
  );    
return $arrResultados;      
}