<?php
/** 
* Modulo de historial de compras
* creado por Ricardo Aguilera
* ricardo.aguilera@playfullinteractive.com
* Módulo para crear los boloques qie irán dentro del historial de compras
* Diseñado para el Proyecto de Future Education.
* Octubre 2014
*
*
*/
/**
* ====================LEEME====================
* Para que éste módulo funcione adecuadamente, se debe de habilitar los siguientes bloques de la manera que se mencina:
* 
* -historial de compras: 
*   Ubicarlo en el main content y configurarlo para que se 
*   muestre sólo bajo los siguientes paths:
*     cuenta/configurar/historial_compras
*     cuenta/configurar/historial_compras*
*
*
*/

function historialcompras_block_info() {
  $blocks['historialcompras'] = array(
    'info' => t('historial de compras'), 
    'cache' => DRUPAL_NO_CACHE, //there are a number of caching options for this
  );
  return $blocks;
}

function historialcompras_block_view($delta = ''){


  if(user_access('access content')){ //good idea to check user perms here
    // $block['subject'] = t('historialcompras');
     $block['content'] = historialcompras_cargar($delta);

     return $block;
  }

}

function historialcompras_cargar($tipoBusqueda){
  $items = array();
  //$items['path'] = drupal_get_path('module', 'includes'); //no modificar
  $items['tipo'] = $tipoBusqueda; //no modificar
  $items['data'] = historialcompras_consultar_db($tipoBusqueda);
// this is where the $items get sent to your default MYMODULE_BLOCK.tpl.php that gets 
// registered below
  return theme('historialcompras', array('items' => $items)); 
}

//here you are registering your default tpl for the above block 
function historialcompras_theme() {   
  $module_path = drupal_get_path('module', 'historialcompras');

  $base = array(
    'path' => "$module_path/templates",   
  );
  return array(
    'historialcompras' => $base + array(
      'template' => 'historialcompras',  //leave off .tpl.php
      'variables' => array('items' => NULL,),
    ),   
  ); 
}

function historialcompras_consultar_db($tipoBusqueda){


  $arrResultados = array();

  for($i=0;$i<3;$i++){
    array_push($arrResultados,
      array(

        'titulo' => l('Canales ','curso.com'),
        'imagen' => 'http://placehold.it/200x200',
        'datoPrincipal' => l('Ricardo','curso.com'),
        'datoAdicional' => '01/01/2014',
        'comportamientoBoton' => 'Ver Curso',
        'tiles' => 'tile tile tile =)',
        'valor1' => '1,000.00',
        'valor2' => '5 estrellitas =)',
      )
    );
  }
  return $arrResultados;

}



/*function print_historial_compras($nid_curso)
{
    $block = module_invoke('historialcompras', 'block_view', 'historialcompras');
    print_r($block['content']);
}
*/